Numpy(넘파이)
===
---

## 1. "Numpy" 에 대하여
- 다차원 배열 객체, 다양한 파생 객체(예: 마스크된 배열 및 행렬) 및 수학적, 논리, 모양 조작, 정렬, 선택, I/O를 포함한 배열에 대한 빠른 작업을 위한 일련의 루틴을 제공하는 Python 라이브러리.
- NumPy 배열은 많은 수의 데이터에 대한 **고급 수학 및 기타 유형의 연산에 용이**.(Python 내장 시퀸스보다 빠르다.)
- NumPy 배열 클래스는 **ndarray**.
- Numpy 배열의 모든 element는 같은 데이터 타입이어야 한다.
***

In [2]:
import numpy as np  # np로 numpy 임포트

## 2. 배열(Array) 생성
#### 1) 파이썬 리스트를 통해 생성

In [19]:
array1 = np.array([1, 2, 3, 4, 5, 6])  # 1차원 배열 생성
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # 2차원 배열 생성

In [20]:
print(array1[0], array2[0])

1 [1 2 3 4]


#### 2) 동일한 값을 가진 array 생성

In [24]:
array_full_of_7 = np.full((2,4), 7)  # parameter : array_size, element -> 모든 원소가 7인 (2행, 4열)의 배열 생성
array_full_of_7

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 3) 모든 값이 0(1)인 배열 생성

In [73]:
array_of_0_1 = np.full(7, 0)  # 2번 방법 이용
array_of_0_2 = np.zeros(7, dtype = int)  # dtype 키워드 -> 데이터 유형 지정
array_of_0_3 = np.zeros((2,3))  # 다차원 배열
array_of_1 = np.ones((3,3))  # 모든 값이 1인 배열

print(array_of_0_1)
print(array_of_0_2)
print(array_of_0_3)
print(array_of_1)

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 4) 랜덤한 값들로 배열 생성

In [30]:
array_random1 = np.random.random(6)  # numpy 모듈 안에 있는 random 모듈에서, random 함수 사용
array_random2 = np.random.random(6)

print(array_random1)
print(array_random2)

[0.48674348 0.20178174 0.94804904 0.13198997 0.63018431 0.14576127]
[0.94657008 0.97676765 0.55063019 0.16800568 0.10911854 0.46207523]


#### 5) 연속된 값들이 담긴 배열 생성

In [32]:
array_p1 = numpy.arange(6)  # arange(m) : 0부터 m - 1까지의 값들이 담긴 배열 생성
print(array_p1)

array_p2 = numpy.arange(2, 8)  # arange(n, m) : n부터 m - 1까지의 값들이 담긴 배열 생성
print(array_p2)

array_p3 = numpy.arange(1, 10, 3)  # arange(n, ,m, s) : n부터 m - 1까지의 값들 중 간격이 s인 값들이 담긴 배열 생성
print(array_p3)

[0 1 2 3 4 5]
[2 3 4 5 6 7]
[1 4 7]


#### 6) 선형 간격을 둔 값들이 담긴 배열 생성

In [39]:
array_linear_space = np.linspace(0, 10, 6)  # linspace(n, m, s) : n ~ m까지를 선형 간격 s로 나눈 element들을 담은 배열 생성
print(array_linear_space)

[ 0.  2.  4.  6.  8. 10.]


#### 7) 2D 단위 행렬 생성

In [53]:
array_eye1 = np.eye(3)  # 단위 행렬 생성
array_eye2 = np.eye(4, 5, 1)  # eye(N, M, k ,etc..) : N - 행의 개수, M - 열의 개수, k - diagonal이 시작되는 index
print(array_eye1)
print(array_eye2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 8) 2D 대각 행렬 생성

In [69]:
array_diag1 = np.diag([1,2,3,4])  # 1차원 배열 -> 2차원 배열
array_diag2 = np.diag([[1,2,3],[4,5,6],[7,8,9]])  # 2차원 배열 -> 1차원 배열

print(array_diag1)
print(array_diag2)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 5 9]


#### 9) 방데르몽드(Vandermonde) 행렬 생성
: 각 행의 초항이 1인 등비수열로 구성된 행렬

In [76]:
array_van = np.vander((1, 2, 3, 4), 5)

print(array_van)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]


---

## 3. 기존 배열 변형 / 복제 / 결합
#### 1) 기존 배열의 변형

In [84]:
array_origin = np.array([1, 2, 3, 4, 5, 6])
array_part = array_origin[:3]  # 기존의 배열을 복사하는 것이 아니라, 일부분만 가져오는 것이다!
print(array_part)

array_part += 1  # array_part에 1을 더하고 싶을 뿐인데,
print(f'origin = {array_origin}, part = {array_part}')  # array_origin에서 0~2 인덱스에 있는 요소들까지 1이 더해지는 것을 볼 수 있다.

[1 2 3]
origin = [2 3 4 4 5 6], part = [2 3 4]


#### 2) 기존 배열의 복제

In [87]:
array_origin = np.array([1, 2, 3, 4, 5, 6])
array_duplicate = array_origin[:3].copy()  # 기존 배열을 복제한다.

array_duplicate += 1
print(f'origin = {array_origin}, part = {array_duplicate}')  # 두 배열이 별개의 객체가 되었다.

array_flatten = array_origin.flatten

origin = [1 2 3 4 5 6], part = [2 3 4]


#### 3) flatten 과 ravel의 차이 (두 메소드 모두 1차원 배열로 만들어준다.)

In [237]:
array_origin = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])  # 원본 배열

array_flatten = array_origin.flatten()  # flatten의 경우, 새 배열을 변경해도 상위 배열은 불변한다. (복사본)
array_flatten[0] = 0
print(array_origin, array_flatten)

array_ravel = array_origin.ravel()  # ravel의 경우, 새 배열을 변경하면 상위 배열도 변한다. (원본의 변형)
array_ravel[0] = 0
print(array_origin, array_ravel)       

[[1 2 3]
 [7 8 9]
 [4 5 6]] [0 2 3 7 8 9 4 5 6]
[[0 2 3]
 [7 8 9]
 [4 5 6]] [0 2 3 7 8 9 4 5 6]


#### 4) 기존 배열의 결합 (vstack, hstack, block, concatenate)

In [4]:
array1 = np.array([1, 2, 3])  # 배열 선언
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

In [12]:
array_vstack1 = np.vstack((array1, array2, array3))  # vstack : 배열을 열 방향으로 쌓는다.
print(array_vstack1)

array_vstack2 = np.vstack((array4, array5))
print(array_vstack2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [11]:
array_hstack1 = np.hstack((array1, array2, array3))  # vstack : 배열을 행 방향으로 쌓는다.
print(array_hstack1)

array_hstack2 = np.hstack((array4, array5))
print(array_hstack2)

[1 2 3 4 5 6 7 8 9]
[[1 4]
 [2 5]
 [3 6]]


In [146]:
A = np.eye(2) * 2  
B = np.eye(3) * 3
array_block = np.block([
    [A,               np.zeros((2, 3))],  # block : 배열을 조립해준다.
    [np.ones((3, 2)), B               ]
])
print(array_block)

[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [1. 1. 3. 0. 0.]
 [1. 1. 0. 3. 0.]
 [1. 1. 0. 0. 3.]]


In [152]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

array3 = np.concatenate((array1, array2), axis = 0)
print(array3)

[[1 2]
 [3 4]
 [5 6]]


---

## 4. 배열의 정렬
#### .sort() 메소드

In [140]:
array1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])  # 1차원 배열

array_sorted = np.sort(array1)  # 기존 배열의 정렬된 "복사본" 배열을 반환
array_sorted += 1  # 복사본에 1을 

np.ndarray.sort(array1)  # 제자리 정렬 (array1 자체를 정렬한다.)

print(array1, array_sorted)  

array2 = np.array([[1,4,2,3],[7,5,8,6], [0,1,2,3]])  # 2차원 배열

array_F = np.sort(array3, axis = None)  # 정렬 후 flatten
array_UD = np.sort(array3, axis = 0)  # 위에서 아래로 정렬
array_LR = np.sort(array3, axis = 1)  # 좌에서 우로 정렬 (= np.sort(array))

print(array_F)  # axis = None
print(array_UD)  # axis = 0
print(array_LR)  # axis = 1

[1 2 3 4 5 6 7 8] [2 3 4 5 6 7 8 9]
[0 1 1 2 2 3 3 4 5 6 7 8]
[[0 1 2 3]
 [1 4 2 3]
 [7 5 8 6]]
[[1 2 3 4]
 [5 6 7 8]
 [0 1 2 3]]


---

## 5. 배열의 모양과 크기
#### .ndim, .size, .shape

In [155]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(f'Dimension : {array_example.ndim}')  # 차원
print(f'The number of elements : {array_example.size}')  # 총 요소 수
print(f'Shape : {array_example.shape}')  # 모양

Dimension : 3
The number of elements : 24
Shape : (3, 2, 4)


---

## 6. 배열의 재구성

In [163]:
array_example = np.arange(1, 13)
array_reshaped = array_example.reshape(3, 4)  # rows / columns (= np.reshape(array_example, newshape = (3, 4)) )
print(array_example)
print(array_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


---

## 7. 배열 인덱싱(Indexing) 및 슬라이싱(Slicing)

In [174]:
data = np.array([1, 2, 3, 4, 5, 6])

print(data[1], data[:3], data[-3:])  # 인덱싱 (여기서 인덱싱된 부분은 원본 배열의 일부분이다. 복사본 X)

2 [1 2 3] [4 5 6]


In [243]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

print(a[0,3])  # 0행 3열에 있는 요소
print(a[0][3])   # 위와 동일

print(a[:, 0])  # 모든 행의 0번째 열에 있는 요소

print(a[a < 5])   # 조건으로 인덱싱하기

divisible_by_two_array = a % 2 == 0  # Boolean 값을 담은 배열이 반환된다.

divisible_by_two = a[a % 2 == 0]  # a 배열에서 Boolean 값이 True인 요소만 출력된다.

print(divisible_by_two_array)

print(divisible_by_two)

4
4
[1 5 9]
[1 2 3 4]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12]


---

## 8. 배열의 기본 연산
#### 1) 사칙연산

In [190]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([-1, -2, -3, -4, -5])

print(data1 + data2)  # 더하기
print(data1 - data2)  # 빼기  
print(data1 * data2)  # 곱하기
print(data1 * 5)  # 스칼라 곱
print(data1 / data2)  # 나누기

[0 0 0 0 0]
[ 2  4  6  8 10]
[ -1  -4  -9 -16 -25]
[ 5 10 15 20 25]
[-1. -1. -1. -1. -1.]


#### 2) 요소들의 합

In [199]:
data1 = np.arange(1,101)
print(data1.sum())  # 1부터 101까지의 합

data2 = np.arange(1, 13).reshape(3, 4)
print(data2)

print(data2.sum(axis = None))  # 요소들의 총합
print(data2.sum(axis = 0))  # Up-to-down (열)
print(data2.sum(axis = 1))  # Left-to-right (행)

5050
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


#### 3) 최대(max), 최소(min), 평균(mean), 요소들 간의 곱(prod), 표준편차(std)

In [203]:
data = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
                 [0.54627315, 0.05093587, 0.40067661, 0.55645993],
                 [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(data.max(axis = 0))  # 최대(axis = 0 -> 열)
print(data.min(axis = 1))  # 최소(axis = 1 -> 행)
print(data.mean(axis = 0))  # 평균(열)
print(data.prod(axis = 1))  # 요소들 간의 곱(행)
print(data.std(axis = None))  # 모든 요소들의 표준편차

[0.54627315 0.82485143 0.40067661 0.56917101]
[0.17296777 0.05093587 0.12697628]
[0.37459419 0.34958502 0.33678154 0.55889871]
[0.01476228 0.00620385 0.01585143]
0.21392120766089617


---

## 9. 고유 아이템과 개수 구하기

In [224]:
data = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(data)  # 고유 아이템 종류 반환
print(unique_values)

unique_values, indices_list = np.unique(data, return_index = True)  # 고유 아이템 종류와 고유값의 인덱스(처음 나오는 인덱스) 반환
print(unique_values, indices_list)

unique_values, occurrence_count = np.unique(data, return_counts = True)  # 고유 아이템 종류와 고유값의 빈도 수 반환
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20] [ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


---

## 10. 행렬의 전치 및 변형
#### 1) 행렬의 전치(Transpose)

In [226]:
array1 = np.arange(6).reshape(2, 3)
print(array1)

array_transposed = array1.transpose()
print(array_transposed)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


#### 2) 배열 뒤집기

array1 = np.array([1, 3, 2, 4, 5, 6, 8, 7])  # 1차원 행렬
array1_rev = np.flip(array1)  # 행렬 뒤집기
print(array_rev)

array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # 2차원 행렬
array2_rev_all = np.flip(array2)  # 모든 행과 열의 내용 뒤집기
array2_rev_row = np.flip(array2, axis = 0)  # 행의 내용 뒤집기
array2_rev_col = np.flip(array2, axis = 1)  # 열의 내용 뒤집기

print(f'all : {array2_rev_all}')
print(f'row : {array2_rev_row}')
print(f'col : {array2_rev_col}')

---

## 11. Docstring 접근

In [241]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [242]:
max?